### ISSUE TITLE
`getOwnerFromDomainTld` throws error when owner cannot be found

### ISSUE THREAD

**Issue by MarcusHSmith** [onsol-labs/tld-parser#20]
```  
const parser = new TldParser(connection)
return await parser.getOwnerFromDomainTld(domain)
  ```
  
Throws the error

```
⨯ TypeError: Cannot read properties of undefined (reading 'owner')
    at /var/task/.next/server/chunks/3078.js:15:23136
    at Generator.next (<anonymous>)
    at o (/var/task/.next/server/chunks/3078.js:15:20926)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```
    
    when domain is a not found
    
    In our test cases the api is passing a solana address, which should not have a owner. However it should fail more gracefully than throwing an exception

**Comment by adpthegreat** [comment]
I get this error too

**Comment by crypt0miester** [comment]
the reason why it is done as such is that so the dev can try catch and identify reasons of failure and parse it accordingly. 

here is a sample code that has been used in the governance-ui code:

https://github.com/Mythic-Project/governance-ui/blob/f860de5ee033bbd5c36169b6d01ba14d0faffd39/hooks/useDestination.ts#L22

**Comment by adpthegreat** [comment]
Alright thanks
