### ISSUE TITLE
`getParsedAllUserDomains(owner)` throws error TypeError: Max seed length exceeded

### ISSUE THREAD

**Issue by adpthegreat** [onsol-labs/tld-parser#23]
So I was trying to use `getParsedAllUserDomains(owner)` to retrieve the user domains associated with a particular public key , so I wrote some example tests to do this 

```typescript
  describe("getOwnedAllDomains", () => {
    it("should return array of domains for an owner", async () => {
      const owner = new PublicKey(
        "2EGGxj2qbNAJNgLCPKca8sxZYetyTjnoRspTPjzN2D67"
      );
      const domains = await agent.getOwnedAllDomains(owner);
      expect(domains).to.be.an("array").that.includes("miester.sol");
      domains.forEach((domain) => {
        expect(domain).to.be.a("string");
      });
    });
    it("should return array of domains for an owner", async () => {
      const owner = new PublicKey(agent.wallet_address);
      const domains = await agent.getOwnedAllDomains(owner);
      expect(domains).to.be.an("array");
      domains.forEach((domain) => {
        expect(domain).to.be.a("string");
      });
    });

    it("should handle owner with no domains", async () => {
      // Create a new random public key that likely owns no domains
      const emptyOwner = PublicKey.unique();
      const domains = await agent.getOwnedAllDomains(emptyOwner);
      expect(domains).to.be.an("array");
      expect(domains).to.have.lengthOf(0);
    });
  });

```

upon running them I got the same error - 

```typescript
   TypeError: Max seed length exceeded
          at forEach (/Users/username/solana-agent-kit/node_modules/.pnpm/@solana+web3.js@1.98.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/@solana/web3.js/src/publickey.ts:175:15)
          at Array.forEach (<anonymous>)
          at Function.createProgramAddressSync (/Users/username/solana-agent-kit/node_modules/.pnpm/@solana+web3.js@1.98.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/@solana/web3.js/src/publickey.ts:173:11)
          at Function.findProgramAddressSync (/Users/username/solana-agent-kit/node_modules/.pnpm/@solana+web3.js@1.98.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/@solana/web3.js/src/publickey.ts:221:24)
          at findTldHouse (/Users/username/solana-agent-kit/node_modules/.pnpm/@onsol+tldparser@0.6.7_@solana+web3.js@1.98.0_bufferutil@4.0.8_utf-8-validate@5.0.10__bn.js@5_27ko3lcyvhk2gu6uwvnrtcsfey/node_modules/@onsol/tldparser/src/utils.ts:266:22)
          at TldParser.<anonymous> (/Users/username/solana-agent-kit/node_modules/.pnpm/@onsol+tldparser@0.6.7_@solana+web3.js@1.98.0_bufferutil@4.0.8_utf-8-validate@5.0.10__bn.js@5_27ko3lcyvhk2gu6uwvnrtcsfey/node_modules/@onsol/tldparser/src/parsers.ts:473:16)
          at Generator.next (<anonymous>)
          at fulfilled (/Users/username/solana-agent-kit/node_modules/.pnpm/@onsol+tldparser@0.6.7_@solana+web3.js@1.98.0_bufferutil@4.0.8_utf-8-validate@5.0.10__bn.js@5_27ko3lcyvhk2gu6uwvnrtcsfey/node_modules/@onsol/tldparser/dist/cjs/parsers.js:5:58)
```

upon further inspection I figured out the cause of the problem , 

I went to the getParsedAllUserDomains function in the parsers.js file in the compiled javascript code and put some console.logs in the for loop to trace the error , basically it first loops through all the TLDs gotten from the getAllTId method 

```typescript 
getParsedAllUserDomains(userAccount) {
        return __awaiter(this, void 0, void 0, function* () {
            const allTlds = yield (0, utils_1.getAllTld)(this.connection);
            let parsedNameAccountsAndDomains = [];
            if (typeof userAccount == 'string') {
                userAccount = new web3_js_1.PublicKey(userAccount);
            }
            for (let { parentAccount, tld } of allTlds) {
                let tldName = tld.toString();
                console.log(`this is the tldName ${tldName}`)
                const [tldHouse] = (0, utils_1.findTldHouse)(tldName);
                console.log(`this is the tldHouse ${tldHouse}`)
```

and it gave me this output 

```typescript
this is the tldName .kingali
this is the tldHouse DsP68VSd1dELdFgms8mtipzeqrtPRvkRcTmDMNUooq7j
this is the tldName .freedom
this is the tldHouse DKwkU8An3ttJ74vKUkYQc52YbwzQyHdNKcpyFnBhK49u
this is the tldName .xyz
this is the tldHouse 8mqV9iXcrjKZaxK95NGFLtapnZ8SgdNwZBuz4gt9CAy9
this is the tldName .blink
this is the tldHouse CD1viBNn8vu8sPiYuPf2tx9SVrpgqP6vEr2ivD4aJtu9
this is the tldName .idx
this is the tldHouse DiKh3v9gKHSBwncDxpN3Paw3vvr42hD8zQDSiqMDt2P9
this is the tldName .token
this is the tldHouse 4n4SJz4eFPf7oKz9HW4GMGe7HC4H2UAUr1855VsqtuPy
this is the tldName .gn
this is the tldHouse 2p8TQ98TXEL4GqfGt1QUS3cMmETEfKrP88A4nSGqXybo
this is the tldName .whatis
this is the tldHouse CxabKRRq7jZD1NhG5gwfNBuBQHv1B4VpbxQPigCGndAD
this is the tldName .nft
this is the tldHouse GZF3xuRk8KncrY6wXZPqd99PyispfqD3xYWso9ez5Xaa
this is the tldName .id
this is the tldHouse Bx2ASGzaKUXusJWGQDqUzBLfQUgJPB5bfWDkGSdcLMS1
this is the tldName .fanestld
this is the tldHouse A2SRYWYfN6DQfGCKji88TM4eNBkQwgcTZ3LvcxixRB1n
this is the tldName .more
this is the tldHouse 8Gi3Z4VHXgtxboK1p5acUUrGb1nSeL1B8UWuD6GZgcpu
this is the tldName .blabla
this is the tldHouse GfkE3kTBWAoa49qXjaGbfCoE7W3p2PWnDYvFKD3b8xQT
this is the tldName .zkk
this is the tldHouse BEdrfTsQ8L8K4SK4t7esMth1j28RPrTrqpcudrqx6h5h
this is the tldName .new
this is the tldHouse DdZH8wgvSBggbUi8ncDat7Tr9kjBcR9ctGcL6nf27qzK
this is the tldName .whatever
this is the tldHouse BuS29eDmrBkK3CM9QZiWJqo5vDW1E7ZZhdL2yqcsHpjv
this is the tldName H�u��)"������I���B��.N&u��

```

the last value is where it threw the error and failed, the TLD most likely has unsupported unicode characters as we can see the garbled output, so when that was passed to the findTldHouse method thats when it threw the error that the max seed length exceeded

```typescript 
function findTldHouse(tldString) {
    tldString = tldString.toLowerCase();
    return web3_js_1.PublicKey.findProgramAddressSync([Buffer.from(constants_1.TLD_HOUSE_PREFIX), Buffer.from(tldString)], constants_1.TLD_HOUSE_PROGRAM_ID);
}
```

**Comment by adpthegreat** [comment]
``` typescript
[ { tld: '.kingali', parentAccount: [PublicKey [PublicKey(5aYQceiTpEFD8TB3GgNHVyLamKnFJ3tfpW9Vgd5cFcUq)]] }, 
{ tld: '.freedom', parentAccount: [PublicKey [PublicKey(9aPhZSJWb1o97ikppehm3XAZqaKCeC72wpHTVNXQj7Ds)]] }, 
{ tld: '.xyz', parentAccount: [PublicKey [PublicKey(H6FEepp8h48XHYF43nwr9avosXkCtgEPF8oyU2Lpd293)]] },
{ tld: '.blink', parentAccount: [PublicKey [PublicKey(GJ2H7fwUuvTvVW5pctHwQzrwPv9X25KAs6hqi9SzK4bU)]] }, 
{ tld: '.idx', parentAccount: [PublicKey [PublicKey(5p7H83D1AZ5eoay3WdP564gozh5nVrRuJbm3MLVzLED5)]] }, 
{ tld: '.token', parentAccount: [PublicKey [PublicKey(FcukpLUf9Y82bmUtoaHNR3QVC4Jg9P6qsFVzU9tHQh3k)]] }, 
{ tld: '.gn', parentAccount: [PublicKey [PublicKey(BEUhEfrJhzVRrrriKV3tp4H6UZbYMiBJBBoH1topnJXV)]] }, 
{ tld: '.whatis', parentAccount: [PublicKey [PublicKey(5jWWTb6ndsG3MQSZnsgoguD7qD6zXSKmEWYPhtQmtvTJ)]] },
 { tld: '.nft', parentAccount: [PublicKey [PublicKey(H3Y7izzoHQ8MzFSkk4kvuJhRarydQc1xUvRBWdSRqiav)]] }, 
{ tld: '.id', parentAccount: [PublicKey [PublicKey(gf7tJLi9bP9Rtkq926H2aEFGsFjw4KUQtGyHKt6WhAX)]] }, 
{ tld: '.fanestld', parentAccount: [PublicKey [PublicKey(62Xu3fjjeLK71NYYK17neSj1P6jytmp6uuxzNSqGSvLg)]] }, 
{ tld: '.more', parentAccount: [PublicKey [PublicKey(PRpbyDBSW323tipkrMTNzKEei946KAgxrJF8hCmNBiK)]] }, 
{ tld: '.blabla', parentAccount: [PublicKey [PublicKey(4vWWsHUVjAvcXeJuhA6Hx7DgkXRvHbyue3XbfVC4BLxE)]] }, 
{ tld: '.zkk', parentAccount: [PublicKey [PublicKey(8XbCdd2zWZNBgWnQ7bunfCE7og7CZ4LsGtqada6d2PHG)]] }, 
{ tld: '.new', parentAccount: [PublicKey [PublicKey(Eq2FHM46PFU6dbrbmNMntv7LsEaw2CH5Si2AufWck1d5)]] }, 
{ tld: '.whatever', parentAccount: [PublicKey [PublicKey(km2pZ73YQg2Rq8fy3HqfeaML8zZHqW54tssTa6FxHSa)]] }, 
{ tld: 'H�u��)"���\x01���I���B�\x13�.N&u��\n', parentAccount: [PublicKey [PublicKey(2EGGxj2qbNAJNgLCPKca8sxZYetyTjnoRspTPjzN2D67)]] }, 
{ tld: 'H�h\x7F�Gׯ&E�|T+\\�ϱ\x1Di��\x16��\x04�\x16\n', parentAccount: [PublicKey [PublicKey(TLDnouMsypo9L4TTzPrpr7MEghoiu3o16RDt5VJRpni)]] }, 
{ tld: '.alinx', parentAccount: [PublicKey [PublicKey(E4AMb8L5sn5oAErnyukqQuUGR6tZKjTmMuvvYEMXF8i)]] }, 
{ tld: '.fanes', parentAccount: [PublicKey [PublicKey(HYnsgoAU2n6Qeu7ypbZbzFQDwDPeQRsTsH9ivQ8u2Y9G)]] }, 
{ tld: '.eth', parentAccount: [PublicKey [PublicKey(GCzHo7kQPQrrLKbcmF3dAb3uv5EG1TxuSqvoNaAdgwHK)]] }, 
{ tld: '.forever', parentAccount: [PublicKey [PublicKey(GQeEamSuhjM6CfCvfmBpsTEcRuDgpTidtxb9KCY4VN7L)]] }, 
{ tld: '.nope', parentAccount: [PublicKey [PublicKey(FDGts76FLJQquSXY7UEAckJRPR7BHWwnEmVYKu1WMsQT)]] }, 
{ tld: '.ali', parentAccount: [PublicKey [PublicKey(4LgPm16KSuDkiaTshEmaZxE2o66HuECyZ9fLzHBFvRmG)]] }, 
{ tld: '.uponly', parentAccount: [PublicKey [PublicKey(9SLUyYfgYfxVHra9hGBFjQBoZHKorzU3fXJ1Hv5SJUwU)]] }, 
{ tld: '.alice', parentAccount: [PublicKey [PublicKey(Av77tMhZZKJgjy4jvnCLKTGCrdPs3Dxdsmo1BkBzDQWE)]] }, 
{ tld: '.x', parentAccount: [PublicKey [PublicKey(8xmDbestndNiUxtJUhaJdCnFXPFXvkWeHLLrdUyTp1M)]] }, 
{ tld: '.fanelu', parentAccount: [PublicKey [PublicKey(7RiHKEAz78wFvGAM5ui14M966JLCnasX4Az4idU48Jtr)]] }, 
{ tld: '.degen', parentAccount: [PublicKey [PublicKey(9Wy6cAaQ1rnF68UzUxJCU7HmTfMZiGgTzNeLHsLHYoX5)]] },
 { tld: '�f�60M8A��%�85��\x02��K�\x12��k��\n', parentAccount: [PublicKey [PublicKey(DaJVVD52pfVRZe7ArD7Y8GSQaUssSxgdtuTKgimtWzCx)]] }, 
{ tld: '.another', parentAccount: [PublicKey [PublicKey(HpEofYTU6D7q3VSkp3cQiY12RJt7ahHHKaHaGpkE8snb)]] }, 
{ tld: '.vault', parentAccount: [PublicKey [PublicKey(Go47mdLvjn23H87e8giTEAPb3toWrYEAiYSHvdXz11XZ)]] }, 
{ tld: '.super', parentAccount: [PublicKey [PublicKey(D5NqiZ74CFzzvutoE1JEeAF1t8shFZzHnashaPmakfEC)]] } ]
``` this is the full list of TLDs , some of them have garbled characters, I wonder why , probably they are emojis ?

**Comment by adpthegreat** [comment]
Please can you assist me @crypt0miester ? thank you

**Comment by crypt0miester** [comment]
you're in devnet I presume. devnet has test cases of us breaking things.

**Comment by adpthegreat** [comment]
thank you, this would be great!
